spring.h2.console.enabled=true
server.ssl.client-auth=want
server.servlet.session.cookie.secure=false

spring.security.oauth2.client.registration.pingfed.client-id=test-client
spring.security.oauth2.client.registration.pingfed.client-secret=test-secret
spring.security.oauth2.client.registration.pingfed.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.pingfed.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.pingfed.scope=openid,profile,email
spring.security.oauth2.client.provider.pingfed.authorization-uri=https://pingfed.example.test/as/authorization.oauth2
spring.security.oauth2.client.provider.pingfed.token-uri=https://pingfed.example.test/as/token.oauth2
spring.security.oauth2.client.provider.pingfed.user-info-uri=https://pingfed.example.test/idp/userinfo.openid
spring.security.oauth2.client.provider.pingfed.user-name-attribute=sub

panel.security.h2-console-enabled=true
panel.security.application-clients[0].name=grafana
panel.security.application-clients[0].certificate-cn=grafana-test
panel.security.application-clients[0].authorities[0]=ROLE_APP_GRAFANA
panel.security.application-clients[0].claims.environment=test
