spring.h2.console.enabled=false
server.ssl.client-auth=want
server.servlet.session.cookie.secure=true

spring.security.oauth2.client.registration.pingfed.client-id=${PINGFED_CLIENT_ID}
spring.security.oauth2.client.registration.pingfed.client-secret=${PINGFED_CLIENT_SECRET}
spring.security.oauth2.client.registration.pingfed.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.pingfed.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.pingfed.scope=openid,profile,email
spring.security.oauth2.client.provider.pingfed.authorization-uri=${PINGFED_AUTHORIZATION_URI}
spring.security.oauth2.client.provider.pingfed.token-uri=${PINGFED_TOKEN_URI}
spring.security.oauth2.client.provider.pingfed.user-info-uri=${PINGFED_USER_INFO_URI}
spring.security.oauth2.client.provider.pingfed.user-name-attribute=${PINGFED_USERNAME_ATTRIBUTE:sub}

panel.security.h2-console-enabled=false
panel.security.application-clients[0].name=${GRAFANA_CLIENT_NAME:grafana}
panel.security.application-clients[0].certificate-cn=${GRAFANA_CERT_CN}
panel.security.application-clients[0].authorities[0]=ROLE_APP_GRAFANA
panel.security.application-clients[0].claims.environment=prod
